### ISSUE TITLE
Stream still starts even when room creation fails

### ISSUE THREAD

**Issue by JohnmarkBeaty** [codysherman/2nfm#107]
So I am noticing that when I test this it _does_ start a stream. 
I'm not sure if we can check before the share screen pops up? If not, we should immediately end the stream.

_Originally posted by @JohnmarkBeaty in https://github.com/codysherman/2nfm/pull/98_

**Comment by samtheprogram** [comment]
Some additional clarity: although issue #96 / PR #98 provides an error message if you choose the same name as an existing stream, and the UI does not show that it is streaming (correctly), `getDisplayMedia` is still open -- so the browser still indicates it is streaming although the 2NFM UI does not.

**Comment by codysherman** [comment]
Fixed in https://github.com/codysherman/2nfm/pull/200
