### ISSUE TITLE
Add pause button after video is clicked played

### ISSUE THREAD

**Issue by cocolin041** [codysherman/2nfm#116]
* Currently, when user click the play button, it will hidden the play button and users have to click the video screen to pause it. As a user, I think it's not good in user experience.
![螢幕快照 2020-02-29 下午4 47 21](https://user-images.githubusercontent.com/26597647/75616158-53ffca00-5b13-11ea-98a7-025210861d60.png)

* Suggestion: Switch the play button into pause button after users click play, and switch pause button to play button after they click pause.

**Comment by jaelder2** [comment]
I'll look into this
