### ISSUE TITLE
h.264 codec support

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#139]
Re-enable the choice of codec, however this might have to be a pro feature, as the older codecs would increase the cost of the TURN server.

**Comment by codysherman** [comment]
H.264 is commented out because it uses a tremendous amount of data vs VP9

**Comment by codysherman** [comment]
Partially implemented via f3ea111bd56436e820a5ea5850bb5eeb2b9d872c

Leaving ticket open to turn this into a pro feature with more codecs.

**Comment by samtheprogram** [comment]
Thinking we could disable the use of the TURN server if h.264 is used, which is something we would like the ability to use for other tasks e.g. #146 -- I may look into implementing this.
