### ISSUE TITLE
Attempt to remove the "background" window running during a cast

### ISSUE THREAD

**Issue by codysherman** [codysherman/2NFM#15]
Does the background window need to exist? While casting an invisible window is open.

**Comment by codysherman** [comment]
On Chrome OS at least, while casting an invisible "background" window is open on the desktop. It's visible in screens such as Overview.

**Comment by codysherman** [comment]
![Screenshot 2019-04-15 at 4 17 58 PM](https://user-images.githubusercontent.com/371608/56165989-18f7b500-5f9a-11e9-99dc-f85d08fd6505.png)

**Comment by bfrisch1** [comment]
![image](https://user-images.githubusercontent.com/12874801/56166008-257c0d80-5f9a-11e9-8d8e-1700c5527ace.png)

**Comment by codysherman** [comment]
No longer needed because the extension requirement has been dropped.
