### ISSUE TITLE
Allow viewers to disable video or audio

### ISSUE THREAD

**Issue by JohnmarkBeaty** [codysherman/2nfm#153]
Right now, would it be possible to stream video and audio separately? 

**Potential use case:**
As a user, I want to listen to the music you are streaming, but don't want/need the video stream as well.

**Questions:**
Would this increase the overall data transmitted? 
Would we have a hard time syncing video to audio?

**Comment by codysherman** [comment]
On the receiver side it wouldn't be hard to chop off the video and just use the audio player, but that wouldn't reduce bandwidth. To also reduce bandwidth the streamer side would have to split, and that would mean sending out different streams based on what the user wants, which would be much tougher.

Syncing wouldn't be an issue, with how MediaStream objects already work, the audio and video are already separate inside the MediaStream object. There is and array for video tracks and an array for audio tracks.
