### ISSUE TITLE
First tab title is not sent to users.

### ISSUE THREAD

**Issue by samtheprogram** [codysherman/2NFM#16]
The first chat message sent to listeners of the stream, i.e. when the `<title>` tag is first read when the stream begins, does not get sent out.

The initial problem is that the [connection used in captureTabUsingTabCapture.js](https://github.com/codysherman/2NFM/blob/b53e3961336d9d2f7c121e0d15a6c122285a303d/background/captureTabUsingTabCapture.js#L94) is not initialized at the time of the first call to sendChatMessage / when the title of the tab is first read.

However, if a callback parameter is added and is passed through `gotTabCaptureStream`, to `gotStream`, to `setupWebRTCConnection`, all the way to `shareStreamUsingRTCMultiConnection`, such that sendChatMessage is not called until the connection is initialized, this still won't work. By the time the client is connected to the stream, the message has already been sent and the client will not receive it, by the nature of a primitive websocket implementation (there is no message history).

So although a hacky solution could be provided for those that are awaiting for the stream to begin, such as delaying the first message sent by 10 seconds, **new** listeners to the stream still wouldn't receive the title of the track.

**Comment by codysherman** [comment]
We have code that detects a new connection (viewer). Let's have it always send the tab title again on that action, and then have a client side duplicate detector (a good idea anyways).
