### ISSUE TITLE
Set video resolution to 144p when using audio only

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#191]
Like how audio only already ignores the user's preference and defaults to h.264 for video, we should investigate whether setting the resolution to 144p also improves performance.

**Comment by samtheprogram** [comment]
Although the h.264 preference change occurs in [StreamerConnection](https://github.com/codysherman/2nfm/blob/0e49190/src/components/StreamerConnection.vue#L132) as it is encoded by WebRTC, the associated place where resolution configuration occurs is in [DesktopCapturer](https://github.com/codysherman/2nfm/blob/0e49190/src/components/DesktopCapturer.vue#L51).
