### ISSUE TITLE
Make "Visit 2N.FM" link in extension go to custom room

### ISSUE THREAD

**Issue by codysherman** [codysherman/2NFM#2]
Make the "Visit 2N.FM" link in the extension go to the custom room if defined. It should also change the text of the button to "Visit 2N.FM/{{room-name-here}}.

**Comment by codysherman** [comment]
Blocked by #11

**Comment by samtheprogram** [comment]
I was going to suggest to have the option to re-open the pop-up window from the dropdown menu (if you are already streaming), but I suppose this will be the way forward?

**Comment by samtheprogram** [comment]
Although the new link in 4794c7f in the provided commit is separate from the current "Visit 2N.FM" button, I'm marking it as resolving this ticket.
