### ISSUE TITLE
Build Improvements

### ISSUE THREAD

**Issue by codysherman** [codysherman/2NFM#22]
This ticket is for improving the build system. Opportunities such as using webpack, etc. Notable improvements would include moving more dependencies to npm, adding support for Sass, etc.

**Comment by codysherman** [comment]
This has a lot of overlap with https://github.com/codysherman/2NFM/issues/50

**Comment by samtheprogram** [comment]
At this rate I would just convert to Vue.js. Switching to Webpack first, then a front-end, doesn't make as much sense given you're going extension-less.

**Comment by codysherman** [comment]
Sounds good, I will close this ticket. Would love to have your help on that Vue conversion, happening over on #50!
