### ISSUE TITLE
Missing text in dark mode

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#238]
![Screenshot 2021-12-15 1 52 36 PM](https://user-images.githubusercontent.com/371608/146255733-517c303a-45c2-483c-b867-7e3e35033ed8.png)

**Comment by codysherman** [comment]
I highlighted the text to show it.

**Comment by Carlos-Gaxiola** [comment]
Hello, can I work on this?

**Comment by codysherman** [comment]
Hi @Carlos-Gaxiola thanks for you interest! If you fork this project and create a branch, you can fix the issue on your branch and then submit a Pull Request on GitHub with your fix.

The set-up instructions are in the README once you've forked and pulled to your machine to get it running locally on localhost.

Hopefully that all makes sense!

A quick note: Due to TURN server private keys not included in this repo, you may find it hard to connect to your own machine's 2N rooms if you're on the the same network. Aka, using one laptop to make a room and another to listen both on the same Wi-Fi. This specific ticket is just a CSS fix so that won't affect you, but if you do want to test streaming, try connecting from your cellular service if you find difficulty connecting to your own rooms.

**Comment by Carlos-Gaxiola** [comment]
Thank you, I will be working on this

**Comment by codysherman** [comment]
Awesome to hear! To push you in the right direction, the solution to this will be that that highlighted text is most like a hard coded color. It needs to be switched to the appropriate CSS variable so that its color shifts based on whether it's in light or dark mode. You should be able to look at other text on the page and see that they are set to CSS variables.

I realize that before you get that far, you have a quite a bit of diving in to do, learning how the app even works in the first place. But as you start to figure out how everything is working, the above should help point you to the correct solution.

Light/dark theme support is quite new to 2n.fm, so recent commits will likely also point you in the right direction as we've fixed other cases of text not properly swapping.

**Comment by Carlos-Gaxiola** [comment]
Nice! Thank you for this guideline

**Comment by Carlos-Gaxiola** [comment]
Hi, I sent a PR to be reviewed

**Comment by pociust** [comment]
should be live shortly, thanks so much for your help!
