### ISSUE TITLE
Receiver sometimes can't stream (TURN)

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#51]
They don't receive the stream, most common when the client is on the same network as the streamer.

**Comment by codysherman** [comment]
I believe I've determined the issue to be lack of functional TURN server.

**Comment by codysherman** [comment]
I've tested the fix of configuring it to use a TURN server using the free developer account from https://xirsys.com. Their free tier provides a 500mb per month. I have it working on my localhost, but I won't be pushing to this repo as it would reveal my personal account.

The final solution will selecting a TURN server ([xirsys](https://xirsys.com) vs [Twilio](https://www.twilio.com/stun-turn)) or possibly hosting one ourselves. The TURN credentials will needed to be added in on deploy, as again, it's not smart to put them into this repo.

**Comment by RobertLowe** [comment]
Twilio will be best and probably cheaper in my opinion.

As I recall there is an API call to generate new TURN credentials which expire after 24? hours by default. You keep your API secret, secret as an environment variable and generate these for the client.
