### ISSUE TITLE
Fix resolution setting

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#57]
In the conversion from extension to website, the resolution setting was severed between captureDesktop.js and onAccessApproved.js.

**Comment by samtheprogram** [comment]
Note that we have removed the resolution related code from the project in #77 , so here's the relevant [commit](https://github.com/codysherman/2NFM/pull/77/commits/ef5743648dbe3aad631a85ba427d4414c792323d) for future retrieval if necessary/desired.

**Comment by codysherman** [comment]
Done in c3a3b8f0c0aa41c4e96c611465dc40749f4ff315
