### ISSUE TITLE
Switch "goog" audio constraints back to optional

### ISSUE THREAD

**Issue by codysherman** [codysherman/2nfm#60]
Was struggling to get the audio constraints to apply with the mandatory system. Temporary have put them all at the top level of the object. This probably breaks some browsers, especially ones that don't start with Google or end with Chrome. Will need to figure out the error that occurs when using the mandatory system.

**Comment by samtheprogram** [comment]
Browsers simply ignore constraints they do not understand, so this shouldn't be an issue. See the green note in "Media Capture and Streams, 11. Constrainable Pattern" [here](https://w3c.github.io/mediacapture-main/#constrainable-interface).
