### ISSUE TITLE
Solve the `--no-engines` yarn install requirement

### ISSUE THREAD

**Issue by codysherman** [codysherman/2NFM#69]
The RTCMultiConnection npm package errors due to a node version issue. This requires installing packages via `yarn install --no-engines`. How do we solve this problem? Is it possible to do on our end? Do we just avoid using npm and manually download the package? Do we need to submit a PR to the package's repo?

**Comment by codysherman** [comment]
Reminder to remove the `--no-engines` flag from the README file when solved.

**Comment by samtheprogram** [comment]
[Related issue](https://github.com/muaz-khan/RTCMultiConnection/issues/853) opened against RTCMultiConnection to solve this the "correct way" as I mentioned in PR #70
