### ISSUE TITLE
Review/fix bytesToSize implementation

### ISSUE THREAD

**Issue by samtheprogram** [codysherman/2nfm#79]
Relevant excerpt (currently from [`Receiver.vue`](https://github.com/codysherman/2NFM/blob/master/src/views/Receiver.vue#L309)):

```javascript
bytesToSize(bytes) {
  // TODO: Should this be 1024?
  var k = 1000;
```

S/O to @codysherman for catching this and originally writing the TODO.

**Comment by codysherman** [comment]
Resolved in f10349e37a276d38136a8aeed3933ca9df0dfccc
