### ISSUE TITLE
Unregister event listeners on unmounted events (or where it makes sense).

### ISSUE THREAD

**Issue by samtheprogram** [codysherman/2nfm#82]
Now that this is a Vue app / SPA, and the app never actually closes, we can't rely on page refreshes to handle unregistering event listeners, like [this one](https://github.com/codysherman/2NFM/blob/261285d/src/components/StreamerConnection.vue#L34) in `StreamerConnection`.

We need to remove the event listeners at sensible times so that memory is not leaked (and possible errors occurring) for those switching in and out of Streamer, Receiver, etc.

**Comment by jvuong1029** [comment]
Working on a solution.
