### ISSUE TITLE
Create an error when trying to create a room name that is already in use

### ISSUE THREAD

**Issue by JohnmarkBeaty** [codysherman/2nfm#96]

**Comment by jni77** [comment]
I am working on a solution for this.

**Comment by fabiantorrestech** [comment]
working on this one as well

**Comment by fabiantorrestech** [comment]
will work on a different ticket.

**Comment by jni77** [comment]
#36 also addresses the following
> Should also error when trying to take an existing 2N hardcoded URL, such as `/streamer`.
