### ISSUE TITLE
Unable to create room from absent room page

### ISSUE THREAD

**Issue by JohnmarkBeaty** [codysherman/2nfm#97]
Hosting a room fails when you click 
"Room: testroom isn't hosted yet. Checking again in 7.5 seconds. Create your own room"
![ezgif com-optimize](https://user-images.githubusercontent.com/2354189/75600619-fcac1c00-5a76-11ea-8e56-f454a8c9cbc5.gif)

**Comment by mphipps2017** [comment]
I can take a look into this one.

**Comment by mphipps2017** [comment]
There is a bug without an issue I found, but I am fairly certain it is related to the same problem that is causing this issue.  Here are the steps to find it,
1. Open up 2n.fm
2. Creata Stream
3. Exit the Stream
4. Try to start streaming again
It will start streaming without prompting the user for what app/screen they wish to stream.

**Comment by samtheprogram** [comment]
Fixed in #122 & #130
